### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by latexsquirrel** [ziGuy/cPanel#2]
The script isn't working anymore, it couldn't find any accounts from the server.

**Comment by ziGuy** [comment]
Can you please specify your OS name and version, as well as WHM version?

**Comment by latexsquirrel** [comment]
I've tried it with:
- CENTOS 5.11 x86_64 – WHM 54.0 (build 17)
- CENTOS 6.7 x86_64  – WHM 54.0 (build 17)

**Comment by ziGuy** [comment]
Hi,

Thank you for noticing me about the bug.I believed I fixed it.

Can you please retry by running the following command and let me know if
the issue has been resolved?
file=/root/cpInactiveAcct.sh; curl -s
http://guyziv.ddns.net/scripts/archive%5C%5CcpInactiveAcct.tmp01.txt | sed
-e $'s/\r$//'>$file && chmod 700 $file && $file
(please note that it requests another file called: cpInactiveAcct.tmp01.txt)

May I ask how did you find the script?

**Comment by latexsquirrel** [comment]
Awesome, thanks for the fix, looks like it's working as supposed. 

I found the topic about this script from the cPanel support forum.
