### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by cunninghambr** [ziGuy/cPanel#3]
perfect your script
however I like to know how I can do 2 things
- Delete accounts suspended for more than two months not 3
- Add ips list of cloudflare not to suspend active accounts with this feature

Best regards

michael cunningham

**Comment by ziGuy** [comment]
Sorry but i'm not maintain this script anymore.

Regard the time, if I were you, I would search and replace:
'7776000' with '5184000'
and
'3 months' with '2 months'

Furtheremore I think i've just saw a bug in line 343 and the following:
    timeOfSus=$((($(date +%s)-$(grep SUSPENDTIME /var/cpanel/users/hbiz | cut -d= -f2))/60/60/24))

should be replaced with:
    timeOfSus=$((($(date +%s)-$(grep SUSPENDTIME /var/cpanel/users/$user | cut -d= -f2))/60/60/24))
